# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90c60a36d18a14367e131d8544d221ce30f784de07053f0f1de322f15c35c0979e3e020e16d31ce87df8e7e82122adbc6f263f7a1a4660dbe4dae84f68415bb9

test:
  secret_key_base: 8512d4010dfa2ecc88ffb62c972081296c16e47d687c51fbe698c4181264068c49398994eb498c8b23e3647127988e3f0af4e41adadeca4c0479a7ebf18eedaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
