$(document).ready ->
  showChar = 200
  ellipsestext = '...'
  moretext = 'more'
  lesstext = 'less'
  $('.more').each ->
    content = $(this).html()
    if content.length > showChar
      c = content.substr(0, showChar)
      h = content.substr(showChar - 1, content.length - showChar)
      html = c + '<span class="moreellipses">' + ellipsestext + '&nbsp;</span><span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">' + moretext + '</a></span>'
      $(this).html html
    return
  $('.morelink').click ->
    if $(this).hasClass('less')
      $(this).removeClass 'less'
      $(this).html moretext
    else
      $(this).addClass 'less'
      $(this).html lesstext
    $(this).parent().prev().toggle()
    $(this).prev().toggle()
    false
  return

# ---
# generated by js2coffee 2.2.0
